import { PhoneNumber, Review } from "./types";

export const mockPhoneNumbers: PhoneNumber[] = [
  {
    id: "1",
    number: "0120123456",
    formattedNumber: "0120-123-456",
    area: "フリーダイヤル",
    carrier: "NTT",
    callType: "sales",
    totalReviews: 45,
    totalViews: 1250,
    dangerLevel: 3,
    lastUpdated: "2025-11-20",
    companyName: "○○通信サービス株式会社",
    industry: "通信・インターネット",
    address: "東京都千代田区丸の内1-1-1",
    contact: "0120-123-456",
    nearestStation: "東京駅",
    access: "JR東京駅 徒歩5分",
    website: "https://example.com",
  },
  {
    id: "2",
    number: "0312345678",
    formattedNumber: "03-1234-5678",
    area: "東京都",
    carrier: "NTT東日本",
    callType: "spam",
    totalReviews: 128,
    totalViews: 3420,
    dangerLevel: 5,
    lastUpdated: "2025-11-21",
    companyName: "株式会社○○不動産",
    industry: "不動産",
    address: "東京都新宿区新宿1-2-3",
    contact: "03-1234-5678",
    nearestStation: "新宿駅",
    access: "JR新宿駅 徒歩3分",
    website: "https://example2.com",
  },
  {
    id: "3",
    number: "0661234567",
    formattedNumber: "06-6123-4567",
    area: "大阪府",
    carrier: "NTT西日本",
    callType: "scam",
    totalReviews: 89,
    totalViews: 2100,
    dangerLevel: 5,
    lastUpdated: "2025-11-19",
    companyName: "詐欺業者（注意）",
    industry: "不明",
    address: "不明",
    contact: "06-6123-4567",
    nearestStation: "不明",
    access: "不明",
    website: "-",
  },
  {
    id: "4",
    number: "09012345678",
    formattedNumber: "090-1234-5678",
    area: "携帯電話",
    carrier: "docomo",
    callType: "unknown",
    totalReviews: 12,
    totalViews: 450,
    dangerLevel: 2,
    lastUpdated: "2025-11-18",
    companyName: "-",
    industry: "-",
    address: "-",
    contact: "090-1234-5678",
    nearestStation: "-",
    access: "-",
    website: "-",
  },
  {
    id: "5",
    number: "0120999888",
    formattedNumber: "0120-999-888",
    area: "フリーダイヤル",
    carrier: "KDDI",
    callType: "legitimate",
    totalReviews: 67,
    totalViews: 890,
    dangerLevel: 1,
    lastUpdated: "2025-11-17",
    companyName: "○○株式会社",
    industry: "サービス業",
    address: "東京都港区赤坂1-1-1",
    contact: "0120-999-888",
    nearestStation: "赤坂見附駅",
    access: "東京メトロ赤坂見附駅 徒歩2分",
    website: "https://example5.com",
  },
  {
    id: "6",
    number: "0527654321",
    formattedNumber: "052-765-4321",
    area: "愛知県名古屋市",
    carrier: "NTT西日本",
    callType: "sales",
    totalReviews: 34,
    totalViews: 780,
    dangerLevel: 3,
    lastUpdated: "2025-11-16",
    companyName: "△△保険株式会社",
    industry: "保険",
    address: "愛知県名古屋市中区錦1-1-1",
    contact: "052-765-4321",
    nearestStation: "名古屋駅",
    access: "JR名古屋駅 徒歩7分",
    website: "https://example6.com",
  },
];

export const mockReviews: Review[] = [
  // 電話番号2 (03-1234-5678) のレビュー
  {
    id: "r1",
    phoneNumberId: "2",
    callType: "spam",
    comment: "毎日のようにかかってきます。出ると無言で切れることが多いです。着信拒否をおすすめします。",
    createdAt: "2025-11-21",
    helpful: 45,
    notHelpful: 2,
  },
  {
    id: "r2",
    phoneNumberId: "2",
    callType: "spam",
    comment: "不動産投資の勧誘でした。断っても何度もかけてきます。",
    callerName: "株式会社○○不動産",
    createdAt: "2025-11-20",
    helpful: 32,
    notHelpful: 1,
  },
  {
    id: "r3",
    phoneNumberId: "2",
    callType: "sales",
    comment: "マンション投資の営業電話でした。丁寧でしたが興味がないと伝えても食い下がってきました。",
    createdAt: "2025-11-19",
    helpful: 28,
    notHelpful: 3,
  },
  {
    id: "r2-4",
    phoneNumberId: "2",
    callType: "spam",
    comment: "自動音声で「あなたのパソコンに問題があります」と言ってきました。明らかな詐欺です。",
    createdAt: "2025-11-18",
    helpful: 67,
    notHelpful: 0,
  },
  {
    id: "r2-5",
    phoneNumberId: "2",
    callType: "spam",
    comment: "不在着信が多く、折り返しても繋がりません。迷惑電話の可能性が高いです。",
    createdAt: "2025-11-17",
    helpful: 41,
    notHelpful: 1,
  },
  {
    id: "r2-6",
    phoneNumberId: "2",
    callType: "scam",
    comment: "還付金詐欺の電話でした。個人情報を聞き出そうとしてきました。絶対に応じないでください。",
    createdAt: "2025-11-16",
    helpful: 92,
    notHelpful: 0,
  },
  // 電話番号1 (0120-123-456) のレビュー
  {
    id: "r4",
    phoneNumberId: "1",
    callType: "sales",
    comment: "インターネット回線の乗り換え案内でした。",
    callerName: "○○通信サービス",
    createdAt: "2025-11-18",
    helpful: 15,
    notHelpful: 0,
  },
  {
    id: "r1-2",
    phoneNumberId: "1",
    callType: "sales",
    comment: "光回線のキャンペーンの案内でした。丁寧な対応でしたが、契約には至りませんでした。",
    callerName: "NTT東日本",
    createdAt: "2025-11-17",
    helpful: 8,
    notHelpful: 0,
  },
  {
    id: "r1-3",
    phoneNumberId: "1",
    callType: "legitimate",
    comment: "アンケート調査の電話でした。短時間で終わり、丁寧に対応していただきました。",
    createdAt: "2025-11-16",
    helpful: 12,
    notHelpful: 0,
  },
  // 電話番号3 (06-6123-4567) のレビュー
  {
    id: "r5",
    phoneNumberId: "3",
    callType: "scam",
    comment: "還付金詐欺の電話でした！役所を名乗っていましたが、絶対に信じないでください。",
    createdAt: "2025-11-17",
    helpful: 89,
    notHelpful: 0,
  },
  {
    id: "r3-2",
    phoneNumberId: "3",
    callType: "scam",
    comment: "「あなたのクレジットカードに不正利用がありました」と偽の警告をしてきました。絶対に個人情報を教えないでください。",
    createdAt: "2025-11-16",
    helpful: 76,
    notHelpful: 0,
  },
  {
    id: "r3-3",
    phoneNumberId: "3",
    callType: "spam",
    comment: "投資の勧誘でした。高利回りを謳っていましたが、明らかに怪しい内容でした。",
    createdAt: "2025-11-15",
    helpful: 54,
    notHelpful: 1,
  },
  // 電話番号4 (090-1234-5678) のレビュー
  {
    id: "r4-1",
    phoneNumberId: "4",
    callType: "unknown",
    comment: "不在着信がありましたが、折り返しても繋がりませんでした。",
    createdAt: "2025-11-18",
    helpful: 5,
    notHelpful: 0,
  },
  {
    id: "r4-2",
    phoneNumberId: "4",
    callType: "unknown",
    comment: "着信がありましたが、出ると切れました。",
    createdAt: "2025-11-17",
    helpful: 3,
    notHelpful: 0,
  },
  // 電話番号5 (0120-999-888) のレビュー
  {
    id: "r5-1",
    phoneNumberId: "5",
    callType: "legitimate",
    comment: "カスタマーサポートからの電話でした。問い合わせへの回答で、丁寧に対応していただきました。",
    callerName: "○○株式会社",
    createdAt: "2025-11-17",
    helpful: 18,
    notHelpful: 0,
  },
  {
    id: "r5-2",
    phoneNumberId: "5",
    callType: "legitimate",
    comment: "サービス更新の案内でした。必要に応じて対応できるよう、分かりやすく説明していただきました。",
    createdAt: "2025-11-16",
    helpful: 14,
    notHelpful: 0,
  },
  // 電話番号6 (052-765-4321) のレビュー
  {
    id: "r6-1",
    phoneNumberId: "6",
    callType: "sales",
    comment: "不動産の営業電話でした。マンション投資の案内でしたが、丁寧に断りました。",
    createdAt: "2025-11-16",
    helpful: 12,
    notHelpful: 1,
  },
  {
    id: "r6-2",
    phoneNumberId: "6",
    callType: "sales",
    comment: "生命保険の案内でした。押しが強く、何度も断る必要がありました。",
    createdAt: "2025-11-15",
    helpful: 8,
    notHelpful: 2,
  },
];

export function getPhoneByNumber(number: string): PhoneNumber | undefined {
  const cleanNumber = number.replace(/[-\s]/g, "");
  return mockPhoneNumbers.find((p) => p.number === cleanNumber);
}

export function getReviewsByPhoneId(phoneNumberId: string): Review[] {
  return mockReviews.filter((r) => r.phoneNumberId === phoneNumberId);
}

export function getRecentPhoneNumbers(limit: number = 6): PhoneNumber[] {
  return [...mockPhoneNumbers]
    .sort((a, b) => new Date(b.lastUpdated).getTime() - new Date(a.lastUpdated).getTime())
    .slice(0, limit);
}
